---
Name: silverstripe-search
---

Page:
  extensions:
    - Pixelpoems\Search\Extensions\SearchIndexExtension

PageController:
  extensions:
    - Pixelpoems\Search\Extensions\PageControllerExtensions
