---
Name: silverstripe-fuse-search
---

Page:
  extensions:
    - Pixelpoems\FuseSearch\Extensions\SearchIndexExtension

PageController:
  extensions:
    - Pixelpoems\FuseSearch\Extensions\PageControllerExtensions
